### ISSUE TITLE
Subject as public

### ISSUE THREAD

**Issue by YonatanAltman** [oriML/swh-assigent#4]
https://github.com/oriML/swh-assigent/blob/de4096dadc6dc886987cbe72f185e2a3e970cd67/src/app/components/countries/countries-container/countries-container.component.html#L1

You do not want to expose your data as a public subject. 
I someone will do `this.countriesService.countries$.next([some data])`.
Use 
```typescript
public get allCountries$(): Observable<Country[]>{
  return this.countries$.asObservable();
}
```

**Comment by oriML** [comment]
Indeed, tnx for highlighting
