### ISSUE TITLE
Reactive Forms

### ISSUE THREAD

**Issue by YonatanAltman** [oriML/swh-assigent#6]
https://github.com/oriML/swh-assigent/blob/de4096dadc6dc886987cbe72f185e2a3e970cd67/src/app/components/country-form/country-form.component.ts#L85

It seems that you don't understand how to use reactive forms correctly. 
You need to use the Controller name inside a form. And when "value changes", which is an angular form's event you can use the "value".
Another problem is that you subscribe to an Observable without unsubscribing when the component is destroyed.

**Comment by oriML** [comment]
@YonatanAltman plz seperate between two forms at this component scope:
1. the data form
2. the criteria form

the criteriaNameControl refers to the **criteria** form control which reacts to changes and trigger an http request to fetch the countries list by user input.
The **name** control value of the data form is being changed by the selection from the autocomplete options on optionSelected() event, accordig to user selection.

I did subscribed to the observable and unsubscribed to it by takeWhile operator, plz see location here - https://github.com/oriML/swh-assigent/blob/de4096dadc6dc886987cbe72f185e2a3e970cd67/src/app/components/country-form/country-form.component.ts#L41.

The takeWhile operator completes the observable when the value of its predicate changed to false, plz see ref on docs - https://rxjs.dev/api/operators/takeWhile.

The fix I need to do here is ref the predicate as:

const parent = this;
takeWhile(() => parent.keepAlive)

**Comment by oriML** [comment]
unsubscribe bug fixed
